# GeminiOrbiter Configuration File

server:
  host: "0.0.0.0"
  port: 8000
  api_key: null

cors:
  allow_origins: ["*"]
  allow_credentials: true
  allow_methods: ["*"]
  allow_headers: ["*"]

gemini:
  secure_1psid: "YOUR_SECURE_1PSID_HERE"  # 必填: 请在此处填入您的 Gemini API Secure 1PSID
  secure_1psidts: "YOUR_SECURE_1PSIDTS_HERE"  # 必填: 请在此处填入您的 Gemini API Secure 1PSIDTS
  timeout: 300

logging:
  level: "DEBUG"