version: "3"

services:
  gemini-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./main.py:/app/main.py
    environment:
      - SECURE_1PSID=${SECURE_1PSID}
      - SECURE_1PSIDTS=${SECURE_1PSIDTS}
    restart: unless-stopped
