# GeminiOrbiter Configuration File

server:
  host: "0.0.0.0"
  port: 8000
  api_key: null

cors:
  allow_origins: ["*"]
  allow_credentials: true
  allow_methods: ["*"]
  allow_headers: ["*"]

gemini:
  secure_1psid: "YOUR_SECURE_1PSID_HERE"
  secure_1psidts: "YOUR_SECURE_1PSIDTS_HERE"
  timeout: 60
  auto_refresh: true
  verbose: false

logging:
  level: "DEBUG"